# Generated by Django 5.2.8 on 2025-12-03 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor_Val',
            fields=[
                ('id_factor', models.AutoField(primary_key=True, serialize=False)),
                ('rango_minimo', models.DecimalField(decimal_places=1, max_digits=12)),
                ('rango_maximo', models.DecimalField(decimal_places=1, max_digits=12)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoNI',
            fields=[
                ('id_instru', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('regla_es', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion_permiso', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion_rol', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('_email', models.CharField(db_column='email_encrypted', default='fake@example.com', max_length=255, unique=True)),
                ('rut', models.CharField(db_index=True, max_length=12, unique=True)),
                ('activo', models.CharField(default='S', max_length=1)),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Miapp.rol')),
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id_cm', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='cargas_masivas/%Y/%m/%d/')),
                ('errores', models.TextField(blank=True)),
                ('procesado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id_busqueda', models.AutoField(primary_key=True, serialize=False)),
                ('criterios_busqueda', models.TextField()),
                ('usuario_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_Auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('tabla', models.CharField(blank=True, max_length=50, null=True)),
                ('cambios', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('firma_digital', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miapp.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miapp.rol')),
            ],
            options={
                'unique_together': {('rol', 'permiso')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('calid', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('factor', models.DecimalField(decimal_places=1, max_digits=10)),
                ('periodo', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('ELIMINADO', 'ELIMINADO'), ('PENDIENTE', 'PENDIENTE')], default='ACTIVO', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('factor_val_id_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Miapp.factor_val')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Miapp.instrumentoni')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_eliminadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('puede_crear_calificacion', 'Puede crear calificación'), ('puede_editar_calificacion', 'Puede editar calificación'), ('puede_eliminar_calificacion', 'Puede eliminar calificación'), ('puede_ver_todas_calificaciones', 'Puede ver todas las calificaciones'), ('puede_carga_masiva', 'Puede realizar carga masiva')],
                'indexes': [models.Index(fields=['periodo'], name='Miapp_calif_periodo_605501_idx'), models.Index(fields=['instrumento'], name='Miapp_calif_instrum_228f3f_idx'), models.Index(fields=['estado'], name='Miapp_calif_estado_a8c6da_idx'), models.Index(fields=['usuario_id_usuario'], name='Miapp_calif_usuario_4f09fe_idx'), models.Index(fields=['monto'], name='Miapp_calif_monto_b087f5_idx')],
            },
        ),
    ]
