# Generated by Django 5.2.7 on 2025-11-03 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('calid', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('factor', models.FloatField()),
                ('periodo', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Factor_Val',
            fields=[
                ('id_factor', models.AutoField(primary_key=True, serialize=False)),
                ('rango_minimo', models.FloatField()),
                ('rango_maximo', models.FloatField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentoNI',
            fields=[
                ('id_instru', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('regla_es', models.TextField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion_permiso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion_rol', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id_cm', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.BinaryField()),
                ('errores', models.TextField()),
                ('calificacion_calid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miapp.calificacion')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='factor_val_id_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miapp.factor_val'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miapp.instrumentoni'),
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miapp.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miapp.rol')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('activo', models.CharField(max_length=1)),
                ('rol_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Miapp.rol')),
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='usuario_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id_busqueda', models.AutoField(primary_key=True, serialize=False)),
                ('criterios_busqueda', models.TextField()),
                ('usuario_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_Auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=255)),
                ('Tabla', models.CharField(max_length=255)),
                ('Cambios', models.TextField()),
                ('Fecha', models.DateField()),
                ('ip', models.CharField(max_length=255)),
                ('Firma_Digital', models.CharField(max_length=255)),
                ('usuario_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
