# Generated by Django 5.2.8 on 2025-12-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Miapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rut_hash',
        ),
    ]
