# Generated by Django 5.2.7 on 2025-11-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
