# Generated by Django 5.2.8 on 2025-11-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miapp', '0003_alter_userauth_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='_email',
            field=models.CharField(db_column='email_encrypted', default='fake@example.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut_hash',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='Fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cargamasiva',
            name='archivo',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='cargamasiva',
            name='calificacion_calid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Miapp.calificacion'),
        ),
        migrations.AlterField(
            model_name='cargamasiva',
            name='errores',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.CharField(default='S', max_length=1),
        ),
    ]
