# Generated by Django 5.2.8 on 2025-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miapp', '0004_remove_usuario_email_usuario__email_usuario_rut_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut_clean',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
    ]
