# Generated by Django 5.2.8 on 2025-11-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Miapp', '0005_usuario_rut_clean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rut_clean',
            new_name='rut',
        ),
    ]
