# Generated by Django 5.2.8 on 2025-11-28 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miapp', '0006_rename_rut_clean_usuario_rut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={'permissions': [('puede_crear_calificacion', 'Puede crear calificación'), ('puede_editar_calificacion', 'Puede editar calificación'), ('puede_eliminar_calificacion', 'Puede eliminar calificación'), ('puede_ver_todas_calificaciones', 'Puede ver todas las calificaciones'), ('puede_carga_masiva', 'Puede realizar carga masiva')]},
        ),
        migrations.RenameField(
            model_name='auditoria',
            old_name='Cambios',
            new_name='cambios',
        ),
        migrations.RenameField(
            model_name='auditoria',
            old_name='Firma_Digital',
            new_name='firma_digital',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='Fecha',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='Tabla',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='usuario_id_usuario',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='calificacion_calid',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_eliminadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('ELIMINADO', 'ELIMINADO'), ('PENDIENTE', 'PENDIENTE')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='factor_val_id_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Miapp.factor_val'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Miapp.instrumentoni'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='usuario_id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cargamasiva',
            name='archivo',
            field=models.FileField(upload_to='cargas_masivas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='factor_val',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='factor_val',
            name='rango_maximo',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factor_val',
            name='rango_minimo',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='instrumentoni',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='instrumentoni',
            name='regla_es',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='descripcion_permiso',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion_rol',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Miapp.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(db_index=True, default='00000000-0', max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together={('rol', 'permiso')},
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['periodo'], name='Miapp_calif_periodo_605501_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['instrumento'], name='Miapp_calif_instrum_228f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['estado'], name='Miapp_calif_estado_a8c6da_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['usuario_id_usuario'], name='Miapp_calif_usuario_4f09fe_idx'),
        ),
        migrations.AddIndex(
            model_name='calificacion',
            index=models.Index(fields=['monto'], name='Miapp_calif_monto_b087f5_idx'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='tabla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
