# Generated by Django 5.2.8 on 2025-11-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Miapp', '0007_alter_calificacion_options_and_more'),
    ]

    operations = [
    ]
