# Generated by Django 5.2.8 on 2025-12-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miapp', '0008_auto_20251130_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor_val',
            name='rango_maximo',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='factor_val',
            name='rango_minimo',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
    ]
